In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [31]:
matrix1=np.array([[1,3]])
matrix2=((np.array([[3,4]])).T)
result1=np.matmul(matrix2,matrix1)
result=np.zeros((2,2))
result=result+result1
result_div=result/4
result_mul=result*5
print(matrix1)
print(matrix2)
print(result1)
print(result)
print(result_div)
print(result_mul)

[[1 3]]
[[3]
 [4]]
[[ 3  9]
 [ 4 12]]
[[ 3.  9.]
 [ 4. 12.]]
[[0.75 2.25]
 [1.   3.  ]]
[[15. 45.]
 [20. 60.]]


In [29]:
x=np.array([[1,2],[3,4],[5,6],[7,8]])
print(x)

m1=np.mean(x,axis=0,keepdims=True)
print(m1)
for xi in x:
    xi =np.array([xi])
    print(xi)
    print((xi-m1).T)
    print(xi-m1)
    temp = np.matmul(((xi-m1).T),(xi-m1))
    print(temp)

print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[4. 5.]]
[[1 2]]
[[-3.]
 [-3.]]
[[-3. -3.]]
[[9. 9.]
 [9. 9.]]
[[3 4]]
[[-1.]
 [-1.]]
[[-1. -1.]]
[[1. 1.]
 [1. 1.]]
[[5 6]]
[[1.]
 [1.]]
[[1. 1.]]
[[1. 1.]
 [1. 1.]]
[[7 8]]
[[3.]
 [3.]]
[[3. 3.]]
[[9. 9.]
 [9. 9.]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
import numpy as np

# 创建一个示例数组
arr = np.array([1, 5, 3, 7, 7, 2, 7, 8])

# 找到满足条件的元素的索引
indices = np.where(arr == 7)

print("满足条件的元素索引：", indices)


满足条件的元素索引： (array([3, 4, 6], dtype=int64),)
