In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

breast_cancer_data = load_breast_cancer()
x = breast_cancer_data.data
y =breast_cancer_data.target
feature_names = breast_cancer_data.feature_names
#malignant=0,benign=1

#label 0 
x_label_0 = x[y==0]
x_label_1 = x[y==1]
y_label_0 = y[y==0]
y_label_1 = y[y==1]
#print(x_label_0[:,-1])
#print(x_label_0.shape)
temp_feature= [22, 24 ,20]
x_1 =x[ : , temp_feature]
print(x[:,[24,20]])
print(x_1)

[[ 0.1622  25.38   ]
 [ 0.1238  24.99   ]
 [ 0.1444  23.57   ]
 ...
 [ 0.1139  18.98   ]
 [ 0.165   25.74   ]
 [ 0.08996  9.456  ]]
[[1.846e+02 1.622e-01 2.538e+01]
 [1.588e+02 1.238e-01 2.499e+01]
 [1.525e+02 1.444e-01 2.357e+01]
 ...
 [1.267e+02 1.139e-01 1.898e+01]
 [1.846e+02 1.650e-01 2.574e+01]
 [5.916e+01 8.996e-02 9.456e+00]]
